### ISSUE TITLE
Add $1,000 tokens to /warp bank (MidnightSky_'s suggestion)

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#176]
**Brief Description**

Self-explanatory

**Why do you want the feature?**

"Reason being in cases where the player wants to limit their random expendatures, it would be nice to have a larger token as opposed to having hundreds of 100$ tokens if not thousands of them, would make storing them a bit cleaner imo... it would also make doing player driven givaways/drop parties a bit simpler." -MidnightSky_

**Comment by Pemigrade** [comment]
Would require me to modify the bank, so it's probably more work than it's worth for something low priority. I'll see if I can get around to it.
