### ISSUE TITLE
People who are muted can talk in #global, #sabotage, join voicechats, and use /msg, /w and /r to reply to others.

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#37]
**Describe the bug**

Muted people can talk in #global or #sabotage and have their messages be sent in chat, they can also join vcs to talk to others and use /r and /msg to talk to others.

**Expected behavior**

If someone is muted they shouldn't be able to speak in any way but they can using the discord.

**To Reproduce**
1. Mute someone
2. Have them talk in #global, #sabotage, join a vc and speak, or use /msg, /w or /r to talk to others.
3. See error

**Comment by manbrodude** [comment]
people who are muted can also join voicechats

**Comment by Pemigrade** [comment]
I think wel'll have to wait for the LiteBans developer to implement a way to do this: https://gitlab.com/ruany/litebans-php/-/issues/72

If they don't, we might just switch to Essentials for some or all punishments.
