### ISSUE TITLE
Re-add party chat / iJoa's Suggestion

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#59]
**Brief Description**

Re-add party chats for people and their friends to communicate in.

**Why do you want the feature?**

"I just wanna say that once there is 2-3 people speaking Spanish in this server even if it is in dms they could lure in more people and to make this possible I think it would be a great idea to make a separate chat for Spanish so people are not breaking the rule but can read what other people are saying even if they are not linked to it. The big picture is seeing our chat with just msgs. How many things would you lose out off if there was no global chat? This is to include and persuade more chatter in Spanish. If there are 3 people speaking spanish and they use the dms the first person would have to send the chat to 2 then each person has to send it to the other 2. Maybe the server is not big enough for that to happen but I think it would be a good adition as we might get 1 Spanish player per week they could really add up. So I’m re suggesting that party chats are introduced" -iJoa

**Comment by Pemigrade** [comment]
https://github.com/MultiChat/Development/issues/110
