### ISSUE TITLE
Allow additional /ah slots to be purchased for votepoints.

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#72]
**Brief Description**

Create a vote perk where people can purchase one /ah slot for 50 VP up until a max of +5 /ah slots.

**Why do you want the feature?**

It would add more things for people to unlock on the /vshop and give people more reason to vote, as well as make the /ah not as empty.

**Comment by Sonic-Probe** [comment]
An alternate proposal that would fit the issue would be 2-5 50-100vp options for an additional /ah slot. That would be more flexible and avoid someone posting 100 items while still allowing 4-7 posts

**Comment by vinceingithub** [comment]
Updated the suggestion to be closer to what sonic said.
