### ISSUE TITLE
Make /list sorted by rank

### ISSUE THREAD

**Issue by vinceingithub** [kakduman/Acorn#82]
**Brief Description**

Make /list list players in increasing order based on rank like the tab menu

**Why do you want the feature?**

It's easier to identify people by rank

**Comment by Pemigrade** [comment]
Option 1, 2, or 3?
(1)
Staff: Founders, Admins, Mods, Helpers, Trainees (in that order)
Players: Withers, Phantoms, Creepers, Spiders, Strays, Skeletons, Drowneds, Husks, Zombies (in that order)

(2)
Staff: Founders, Admins, Mods, Helpers, Trainees (in that order)
Withers: Withers
Phantoms: Phantoms
Creepers: Creepers
Spiders: Spiders
Strays: Strays
Skeletons: Skeletons
Drowneds: Drowneds
Husks: Husks
Zombies: Zombies

(3)
Admins: Founders, Admins
Mods: Mods
Helpers: Helpers
Trainees: Trainees
Withers: Withers
Phantoms: Phantoms
Creepers: Creepers
Spiders: Spiders
Strays: Strays
Skeletons: Skeletons
Drowneds: Drowneds
Husks: Husks
Zombies: Zombies

**Comment by manbrodude** [comment]
Option 1. Options 2 and 3 are too long/messy in my opinion.

**Comment by Pemigrade** [comment]
Agreed. Unfortunately there's no way to sort within a group with Essentials, so only option 2 and 3 would work. There would be no way to sort staff by rank either.

Between option 2, 3, and the current /list, which do you think would be best?

**Comment by manbrodude** [comment]
Then in that case, hard 2.
